#!/usr/bin/env python3
"""Extract BASE_PRESETS / CITIES / ROOM_TYPES from the source index.html into a
Python module (bot/app/presets.py). Parsing the canonical source keeps the bot's
material library byte-for-byte identical to the website instead of hand-copying
115+ entries.
"""
import re
import os
import json

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, "index.html")
OUT = os.path.join(ROOT, "bot", "app", "presets.py")

with open(SRC, encoding="utf-8") as f:
    lines = f.readlines()


def grab_block(start_marker, end_marker, from_line=0):
    started = False
    buf = []
    for i, ln in enumerate(lines):
        if i < from_line:
            continue
        if not started and start_marker in ln:
            started = True
        if started:
            buf.append(ln)
            if end_marker in ln and len(buf) > 1:
                return buf, i
    return buf, len(lines)


def parse_preset_line(ln):
    if "id:'" not in ln:
        return None
    out = {}
    m = re.search(r"id:'([^']*)'", ln)
    out["id"] = m.group(1)
    m = re.search(r"name:'([^']*)'", ln)
    out["name"] = m.group(1) if m else out["id"]
    m = re.search(r"\br:([0-9.]+)", ln)
    if m:
        out["r"] = float(m.group(1))
    m = re.search(r"group:'([^']*)'", ln)
    if m:
        out["group"] = m.group(1)
    # λ (homogeneous materials) + thickness (walls) → let the UI show λ next to R.
    m = re.search(r"lambda:([0-9.]+)", ln)   # lambda:null (composites) is skipped
    if m:
        out["lambda"] = float(m.group(1))
    m = re.search(r"thickness:([0-9]+)", ln)
    if m:
        out["thickness"] = int(m.group(1))
    m = re.search(r"\bu:([0-9.]+)", ln)       # U-value for windows/doors
    if m:
        out["u"] = float(m.group(1))
    m = re.search(r"\bn:([0-9.]+)", ln)
    if m:
        out["n"] = float(m.group(1))
    if "ground:true" in ln:
        out["ground"] = True
    m = re.search(r"addR:([0-9.]+)", ln)
    if m:
        out["addR"] = float(m.group(1))
    if "recommended:true" in ln:
        out["recommended"] = True
    return out


# BASE_PRESETS block
block, _ = grab_block("const BASE_PRESETS = {", "};")
presets = {"walls": [], "windows": [], "doors": [], "floors": [], "ceilings": []}
cur = None
for ln in block:
    for cat in presets:
        if re.match(r"\s*" + cat + r":\[", ln):
            cur = cat
    p = parse_preset_line(ln)
    if p and cur:
        presets[cur].append(p)

# CITIES
cblock, _ = grab_block("const CITIES = [", "];")
cities = []
for ln in cblock:
    m = re.search(r"id:'([^']*)',name:'([^']*)',region:'([^']*)',t:(-?[0-9.]+)", ln)
    if m:
        cities.append({"id": m.group(1), "name": m.group(2),
                       "region": m.group(3), "t": float(m.group(4))})

# ROOM_TYPES (parse each field independently — source uses mixed quotes/alignment)
rblock, _ = grab_block("const ROOM_TYPES = [", "];")
room_types = []
for ln in rblock:
    mid = re.search(r"id:'([^']*)'", ln)
    if not mid:
        continue
    nm = re.search(r"[^a-zA-Z]name:(['\"])(.*?)\1", " " + ln)
    uz = re.search(r"nameUz:(['\"])(.*?)\1", ln)
    en = re.search(r"nameEn:(['\"])(.*?)\1", ln)
    t = re.search(r"\bt:([0-9.]+)", ln)
    if nm and uz and en and t:
        room_types.append({"id": mid.group(1), "name": nm.group(2), "nameUz": uz.group(2),
                           "nameEn": en.group(2), "t": float(t.group(1))})

counts = {k: len(v) for k, v in presets.items()}
print("preset counts:", counts, "total", sum(counts.values()))
print("cities:", len(cities), "room_types:", len(room_types))

with open(OUT, "w", encoding="utf-8") as f:
    f.write('"""AUTO-GENERATED by scripts/extract_presets.py from index.html. Do not edit by hand."""\n')
    f.write("import json\n\n")
    f.write("BASE_PRESETS = json.loads(r'''" + json.dumps(presets, ensure_ascii=False) + "''')\n\n")
    f.write("CITIES = json.loads(r'''" + json.dumps(cities, ensure_ascii=False) + "''')\n\n")
    f.write("ROOM_TYPES = json.loads(r'''" + json.dumps(room_types, ensure_ascii=False) + "''')\n")

print("wrote", OUT)
